---
# tasks file for php
- name: Ensure php and php-fpm is installed
  ansible.builtin.yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - php
    - php-fpm
- name: Ensure php-fpm is started and enabled
  ansible.builtin.service:
    name: php-fpm
    state: started
    enabled: yes
- name: Replace dfault php-fpm config file
  ansible.builtin.copy:
    src: files/etc/php-fpm.d/www.conf
    dest: /etc/php-fpm.d/www.conf
    backup: yes
  notify:
   - "restart_php-fpm"
- name: Add basic php page
  ansible.builtin.copy:
    src: files/usr/share/nginx/html/index.php
    dest: /usr/share/nginx/html/index.php
  notify:
    - "restart_php-fpm"
- name: Open 9000/tcp for fpm connections
  ansible.posix.firewalld:
    port: 9000/tcp
    permanent: true
    state: enabled
  notify:
    - "restart_firewalld"